### ISSUE TITLE
Hi problem with simple startup on heroku: Postdeploy exit code was not 0

### ISSUE THREAD

**Issue by loyalcollege** [adzialocha/hoffnung3000#106]
[31mERROR:[39m Fields must be specified through options.fields

[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m ELIFECYCLE
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35merrno[0m 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m hoffnung3000@2.0.1 db:migrate: `sequelize db:migrate`
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Exit status 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Failed at the hoffnung3000@2.0.1 db:migrate script.
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m This is probably not a problem with npm. There is likely additional logging output above.
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /app/.npm/_logs/2021-01-04T18_21_39_740Z-debug.log
[0m

**Comment by loyalcollege** [comment]
https://winter2021-loyal.herokuapp.com/

**Comment by adzialocha** [comment]
Thank you for this @loyalcollege, the API for `addConstraints` has apparently been updated in Sequelize v6 (https://sequelize.org/master/manual/upgrade-to-v6.html). I've changed it in this commit, the migrations should work again: https://github.com/adzialocha/hoffnung3000/commit/f80cf796f1ef39f46d6300500172fba9accf99d1
