### ISSUE TITLE
Calendar does not work when user is logged in ( on Heroku install )

### ISSUE THREAD

**Issue by loyalcollege** [adzialocha/hoffnung3000#107]
Hi, I tried the heroku install and after creating an account the calendar throws me the following error:

Not sure this issue is due to the code itself or heroku install…

![Screen Shot 2021-01-17 at 21 42 39](https://user-images.githubusercontent.com/76966333/104852693-7fe39400-590d-11eb-9fe8-3c7de4ec3a0f.png)

**Comment by adzialocha** [comment]
I can see something similar:

`TypeError: this.props.defaultTags is null`

**Comment by adzialocha** [comment]
This was fixed in https://github.com/adzialocha/hoffnung3000/pull/112
