### ISSUE TITLE
hoffnung3000 webserver serves self-signed certificate and only default page

### ISSUE THREAD

**Issue by fwolfst** [adzialocha/hoffnung3000#41]
The link in the README (last paragraph) points to a default plesk site, and the certificate leads to a warning (self signed).

**Comment by adzialocha** [comment]
Hi @fwolfst,

thank you for your message. The project documentation is in heavy rework right now, some pages are outdated, new ones are in the making. The plan is:

* Move old festival page to https://hoffnung3000.herokuapp.com/ (as an archive)
* Write a manual for future users here: https://hoffnung3000.blatt3000.de (http://github.com/adzialocha/hoffnung3000-documentation/)
* Update this repository `README.md` accordingly
