### ISSUE TITLE
Pop-up text still says "HOFFNUNG 3000" even when festival title is changed

### ISSUE THREAD

**Issue by sandreae** [adzialocha/hoffnung3000#55]

**Comment by adzialocha** [comment]
Do you mean these fields here? These might be the one:

https://github.com/adzialocha/hoffnung3000/blob/master/common/locales/flash.en.js#L31-L32

**Comment by sandreae** [comment]
Yes, I think that's probably it. Thanks!

**Comment by adzialocha** [comment]
Re-openend the issue, as there is no fix for it yet 😀

**Comment by adzialocha** [comment]
Solved with https://github.com/adzialocha/hoffnung3000/commit/4300f1be58b46e525010048f76d7ac1bdc33fca0
