### ISSUE TITLE
Venue registration: all slots disabled by default

### ISSUE THREAD

**Issue by sandreae** [adzialocha/hoffnung3000#58]
Slots disabled by default and enabled when selected. Slightly more intuitive for users.

**Comment by sandreae** [comment]
I'm having a go at making this change, thought it might involve changing this value from "false" to "true" but not joy so far. Am I in the right area?

https://github.com/adzialocha/hoffnung3000/blob/b0f0a3018eca0a0411d25f3fceb084aeedd55222/common/utils/slots.js#L110

**Comment by adzialocha** [comment]
The database currently only stores used slots to be more efficient. To get all slots be turned on by default requires a) filling the database with active slots for each event or b) changing the database logic to only hold disabled slots (much better).

Yeah, this requires then changes in the overall logic how a slot is represented internally.

**Comment by sandreae** [comment]
Ah, sorry, I wasn't clear.

I'm suggesting that when registering a _venue_ all slots should be disabled by default.

**Comment by sandreae** [comment]
This is because many of the venues registering for the festival will only have maybe a coupe of periods where they are available within the week long festival. So in this case there are a lot of slots to disable.....

**Comment by adzialocha** [comment]
I see! Still what I've written in the above comment counts. Disabled slots are currently stored in the database, I suggest to change the logic then to storing only active slots when changing the default.

**Comment by adzialocha** [comment]
This is implemented now as a Toggle button!
