### ISSUE TITLE
Name fields do not allow Swedish characters

### ISSUE THREAD

**Issue by muscarina** [adzialocha/hoffnung3000#71]
When registering users with Swedish characters (Charset: ISO-8859-1) in their first or lastname,
 you get the message: 

> _"firstname" must only contain alpha-numeric characters"_

The City, Country fields etc do allow these characters.

**Comment by muscarina** [comment]
Couldn't find anything useful when looking through all the .js files for forms etc containing the words "firstname" or "lastname". 

Could be that the error originates from the database operation to postgres.

**Comment by adzialocha** [comment]
The validation takes place in the backend, exactly here: https://github.com/adzialocha/hoffnung3000/blob/master/server/validation/user.js#L7-L8

This is definitely not ideal, we should just remove the `alphanum` requirement.

**Comment by adzialocha** [comment]
I've pushed a fix here: https://github.com/adzialocha/hoffnung3000/commit/56e470a3167bed5b05cbb610be32ea9708068cea - Thank you for pointing this out @muscarina!

**Comment by muscarina** [comment]
> 
> 
> I've pushed a fix here: [56e470a](https://github.com/adzialocha/hoffnung3000/commit/56e470a3167bed5b05cbb610be32ea9708068cea) - Thank you for pointing this out @muscarina!

Great stuff! Thanks :)
